# Simple workflow for deploying static content to the gh-pages branch
name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Marp Slide
        run: |
          mkdir -p report
          npx @marp-team/marp-cli report/nemo_eda_slides.md -o report/nemo_eda_slides.html
          npx @marp-team/marp-cli report/nemo_eda_slides_neo.md -o report/nemo_eda_slides_neo.html
          npx @marp-team/marp-cli report/nemo_eda_slides_mesh.md -o report/nemo_eda_slides_mesh.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Root directory containing index.html and generated report/nemo_eda_slides.html
          publish_branch: gh-pages
          force_orphan: true

